### PR TITLE
Timeouts for Sentinel Connections

### PR DESCRIPTION
**Pull request by tback**

### CODE REVIEW

**Comment by tback** [comment]
Hi James, let me know if this needs more work. I'd really love to see this merged.

**Comment by jamescauwelier** [comment]
Any chance you can add a test for it @tback ?

**Comment by tback** [comment]
I'd be more than happy to provide a test for the timeout configuration but I didn't find out how to assert that the Clientadapter was instantiated in a certain way.

**Comment by jamescauwelier** [comment]
@tback Can't you work out the first scenario in https://github.com/jamescauwelier/PSRedis/issues/20 and then try a redis command?  The code contains documentation on how to do integration testing which is probably where this type of testing would belong.

**Comment by jamescauwelier** [comment]
@tback let me know what you think?

**Comment by tback** [comment]
@jamescauwelier Thanks, that looks like a better option.

**Comment by jamescauwelier** [comment]
Thank you for the test @tback.  I have not tested this as I don't have the time right now, but can merge into a pre-release.  Will that work for you for now?

**Comment by tback** [comment]
I switched to https://github.com/nrk/predis/tree/v1.1-sentinel, sorry.

**Comment by jamescauwelier** [comment]
I was more than happy to merge this in a pre-release @tback

**Comment by tback** [comment]
I know, thanks for that james. But it seems that nrk started working on https://github.com/nrk/predis/issues/131 again. The code is well integrated with predis, it works, and I've got one less dependency do worry about.

**Pull request closed without merging**
